'use strict';
function renderEbpIncomingView({ files, error, message, incomingDir }, { escHtml, clientPageIcon, formatDateTimeLabel, formatFileSize }) {
  const row = (file) => { const open=`/orders/clients/incoming-ebp/open?file=${encodeURIComponent(file.name)}`; return `<tr><td data-label="Fichier PDF">${escHtml(file.name)}</td><td data-label="Date d'ajout">${escHtml(formatDateTimeLabel(file.addedAt))}</td><td data-label="Taille">${escHtml(formatFileSize(file.size))}</td><td data-label="Actions"><div class="modern-form-actions ebp-file-actions" style="justify-content:flex-start;gap:8px;"><a class="modern-cancel-link ebp-open-link" href="${open}">Ouvrir</a><form method="POST" action="/orders/clients/scan-ebp/analyze-incoming" style="margin:0;"><input type="hidden" name="incoming_file" value="${escHtml(file.name)}" /><button type="submit" class="clients-submit-btn"><span>${clientPageIcon('search','clients-submit-icon')}</span>Scanner ce devis</button></form></div></td></tr>`; };
  const card = (file) => { const open=`/orders/clients/incoming-ebp/open?file=${encodeURIComponent(file.name)}`; return `<article class="ebp-file-card"><div class="ebp-file-card-main"><h2>${escHtml(file.name)}</h2><p><strong>Ajouté le</strong> ${escHtml(formatDateTimeLabel(file.addedAt))}</p><p><strong>Taille :</strong> ${escHtml(formatFileSize(file.size))}</p></div><div class="ebp-file-card-actions"><a class="modern-cancel-link ebp-open-link" href="${open}">Ouvrir</a><form method="POST" action="/orders/clients/scan-ebp/analyze-incoming"><input type="hidden" name="incoming_file" value="${escHtml(file.name)}" /><button type="submit" class="clients-submit-btn"><span>${clientPageIcon('search','clients-submit-icon')}</span>Scanner ce devis</button></form></div></article>`; };
  const rows=files.length?files.map(row).join(''):'<tr><td colspan="4" class="empty">Aucun PDF à traiter dans le dossier incoming.</td></tr>';
  const cards=files.length?files.map(card).join(''):'<div class="empty-state ebp-empty-state">Aucun PDF à traiter dans le dossier incoming.</div>';
  return `<div class="modern-page modern-client-orders-page ebp-page"><section class="modern-list-head modern-client-orders-head ebp-head"><div class="clients-create-head">${clientPageIcon('quotes','clients-title-icon')}<div class="ebp-head-copy"><h1>Devis EBP à traiter</h1><span class="ebp-source-label">Dossier source :</span><span class="ebp-source-path">${escHtml(incomingDir)}</span></div></div></section><section class="clients-create-card modern-form-card modern-client-order-form ebp-card">${error?`<p class="error">${escHtml(error)}</p>`:''}${message?`<p class="info">${escHtml(message)}</p>`:''}<div class="ebp-files-wrapper"><table class="modern-list-table ebp-files-table"><thead><tr><th>Fichier PDF</th><th>Date d'ajout</th><th>Taille</th><th>Actions</th></tr></thead><tbody>${rows}</tbody></table></div><div class="ebp-files-cards" aria-label="Liste mobile des devis EBP à traiter">${cards}</div><div class="modern-form-actions ebp-page-actions"><a class="modern-cancel-link" href="/orders/clients">Retour commandes</a><a class="clients-submit-btn" href="/orders/clients/scan-ebp"><span>${clientPageIcon('quotes','clients-submit-icon')}</span>Scanner via upload</a></div></section></div><script>(function(){var storageKey='incoming-ebp-scroll';try{var saved=window.sessionStorage.getItem(storageKey);if(saved){window.requestAnimationFrame(function(){window.scrollTo(0,Number(saved)||0);window.sessionStorage.removeItem(storageKey);});}}catch{}document.querySelectorAll('.ebp-open-link').forEach(function(link){link.addEventListener('click',function(){try{window.sessionStorage.setItem(storageKey,String(window.scrollY||window.pageYOffset||0));}catch{}});});})();</script>`;
}
function renderEbpIncomingFileView(name, escHtml){const title=escHtml(name),raw=`/orders/clients/incoming-ebp/raw?file=${encodeURIComponent(name)}`;return `<!DOCTYPE html><html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${title}</title><link rel="stylesheet" href="/style.css?v=20260711-2"></head><body class="incoming-pdf-viewer-body"><div class="incoming-pdf-viewer"><header class="incoming-pdf-viewer-header"><button type="button" class="incoming-pdf-back" onclick="goBackToIncomingList()">← Retour</button><strong class="incoming-pdf-title">${title}</strong><a class="incoming-pdf-download" href="${raw}" download="${title}">Télécharger</a></header><main class="incoming-pdf-frame-wrap"><embed src="${raw}" type="application/pdf" class="incoming-pdf-frame"></main></div><script>function goBackToIncomingList(){try{if(window.history.length>1&&document.referrer){window.history.back();return;}}catch{}window.location='/orders/clients/incoming-ebp';}</script></body></html>`;}
module.exports={renderEbpIncomingView,renderEbpIncomingFileView};
