'use strict';
function renderEbpValidationView(data,{escHtml,clientPageIcon}){const options=data.candidates.map(c=>{const selected=data.clientProposed&&data.normalizeSearchText(c.name)===data.normalizeSearchText(data.clientProposed)?' selected':'';return `<option value="${escHtml(c.name)}"${selected}>${escHtml(c.name)} (${escHtml(c.sources.join('+'))})</option>`}).join('');return `<div class="modern-page modern-client-orders-page"><section class="modern-list-head modern-client-orders-head"><div class="clients-create-head">${clientPageIcon('quotes','clients-title-icon')}<div><h1>Validation avant création</h1><span>Aucune commande n'est créée automatiquement. Vérifiez les champs ci-dessous.</span></div></div></section><section class="clients-create-card modern-form-card modern-client-order-form">${data.warning?`<p class="info">${escHtml(data.warning)}</p>`:''}${data.htMissingWithTtc?'<p class="info">Montant TTC détecté, mais aucun montant HT fiable. Renseignez le montant HT avant création si vous voulez afficher un prix chantier HT.</p>':''}<form method="POST" action="/orders/clients/scan-ebp/create" class="modern-client-order-add-form"><input type="hidden" name="scan_file" value="${escHtml(data.scanFileName)}" /><input type="hidden" name="scan_original_name" value="${escHtml(data.scanOriginalName||data.scanFileName)}" /><input type="hidden" name="scan_source" value="${escHtml(data.scanSource)}" />${data.scanSource==='incoming'?`<input type="hidden" name="incoming_file" value="${escHtml(data.incomingFileName)}" />`:''}<div class="modern-form-grid">
<label class="clients-field"><span>Client détecté</span><div class="clients-input-shell">${clientPageIcon('user')}<input name="detected_client" value="${escHtml(data.fields.client_name||'')}" /></div></label>
<label class="clients-field"><span>Client existant proposé</span><div class="clients-input-shell">${clientPageIcon('clients')}<select name="existing_client"><option value="">-- Aucun / créer nouveau --</option>${options}</select></div></label>
<label class="clients-field"><span>Client final (modifiable)</span><div class="clients-input-shell">${clientPageIcon('user')}<input name="client_name" value="${escHtml(data.clientProposed)}" required /></div></label>
<label class="clients-field"><span>Numéro devis</span><div class="clients-input-shell">${clientPageIcon('quotes')}<input name="quote_number" value="${escHtml(data.fields.quote_number||'')}" /></div></label>
<label class="clients-field"><span>Date devis / commande</span><div class="clients-input-shell">${clientPageIcon('calendar')}<input type="date" name="quote_date" value="${escHtml(data.dateProposed)}" /></div></label>
<label class="clients-field"><span>Intitulé commande proposé</span><div class="clients-input-shell">${clientPageIcon('folder')}<input name="description" value="${escHtml(data.descriptionProposed)}" required /></div></label>
<label class="clients-field"><span>Montant HT (€)</span><div class="clients-input-shell">${clientPageIcon('postal')}<input name="amount_ht" type="number" step="0.01" value="${escHtml(data.amountHt)}" /></div></label>
<label class="clients-field"><span>Montant TTC (€)</span><div class="clients-input-shell">${clientPageIcon('postal')}<input name="amount_ttc" type="number" step="0.01" value="${escHtml(data.amountTtc)}" /></div></label>
<label class="clients-field"><span>Si client introuvable</span><div class="clients-input-shell" style="display:flex;gap:8px;align-items:center;"><input id="create_client_if_missing" type="checkbox" name="create_client_if_missing" value="1" checked /><label for="create_client_if_missing" style="margin:0;">Créer le client automatiquement après validation</label></div></label></div><div class="modern-form-actions"><button type="submit" class="clients-submit-btn"><span>${clientPageIcon('add','clients-submit-icon')}</span>Créer la commande (validation manuelle)</button><a class="modern-cancel-link" href="/orders/clients/scan-ebp">Recommencer</a></div></form></section></div>`;}
module.exports={renderEbpValidationView};
