'use strict';
function createEbpScannerController(d={}){const{incomingService,validationService,scannerService,renderIncomingView,renderIncomingFileView,renderScannerView,renderValidationView,pageTemplate,viewDependencies,uploadSingle,path,safeSegment,incomingDir}=d;
 const validation=(req,res,options)=>validationService.buildQuoteValidationData(options).then(data=>res.send(pageTemplate(req,'Validation scan devis EBP',renderValidationView(data,viewDependencies))));
 function showIncoming(req,res){return res.send(pageTemplate(req,'Devis EBP à traiter',renderIncomingView({files:incomingService.listIncomingFiles(),error:String(req.query.error||'').trim(),message:String(req.query.message||'').trim(),incomingDir},viewDependencies)))}
 function openIncoming(req,res){const file=incomingService.resolveIncomingFile(req.query.file||'');if(file.error==='invalid')return res.status(400).send('Nom de fichier PDF invalide');if(file.error)return res.status(404).send('Fichier introuvable');return res.send(renderIncomingFileView(file.name,viewDependencies.escHtml))}
 function rawIncoming(req,res){const file=incomingService.resolveIncomingFile(req.query.file||'');if(file.error==='invalid')return res.status(400).send('Nom de fichier PDF invalide');if(file.error)return res.status(404).send('Fichier introuvable');res.setHeader('Content-Type','application/pdf');res.setHeader('Content-Disposition',`inline; filename="${safeSegment(file.name||'devis.pdf')}"`);return res.sendFile(file.filePath)}
 async function analyzeIncoming(req,res){try{const file=incomingService.copyIncomingForAnalysis(req.body.incoming_file||'');if(file.error==='invalid')return res.redirect('/orders/clients/incoming-ebp?error=Nom+de+fichier+PDF+invalide');if(file.error)return res.redirect('/orders/clients/incoming-ebp?error=Fichier+incoming+introuvable');return await validation(req,res,{scanFileName:file.scanFileName,scanOriginalName:file.name,mimeType:'application/pdf',scanSource:'incoming',incomingFileName:file.name})}catch(error){return res.redirect(`/orders/clients/incoming-ebp?error=${encodeURIComponent(error.message||'Analyse impossible')}`)}}
 function showScanner(req,res){return res.send(pageTemplate(req,'Scanner devis EBP',renderScannerView({error:String(req.query.error||'').trim(),message:String(req.query.message||'').trim()},viewDependencies)))}
 function analyzeUpload(req,res){uploadSingle(req,res,async error=>{if(error)return res.redirect(`/orders/clients/scan-ebp?error=${encodeURIComponent(error.message||'Upload impossible')}`);if(!req.file)return res.redirect('/orders/clients/scan-ebp?error=Aucun+fichier+recu');try{return await validation(req,res,{scanFileName:req.file.filename,scanOriginalName:req.file.originalname||req.file.filename,mimeType:req.file.mimetype,scanSource:'upload'})}catch(e){return res.redirect(`/orders/clients/scan-ebp?error=${encodeURIComponent(e.message||'Analyse impossible')}`)}})}
 function createOrder(req,res){try{const result=scannerService.createOrder(req.body);if(result.error)return res.status(result.errorCode).send(result.error);return res.redirect(result.redirect)}catch(error){return res.status(500).send(`Erreur création depuis scan EBP: ${viewDependencies.escHtml(error.message||'inconnue')}`)}}
 return{showIncoming,openIncoming,rawIncoming,analyzeIncoming,showScanner,analyzeUpload,createOrder};}
module.exports={createEbpScannerController};
