'use strict';
function createMeasurementStairV2Controller(d={}){const{s,photos,parseOptionalId,upload,fs,path,publicDir,logger=console}=d;
 function bootstrap(req,res){return res.json(s.bootstrap({id:parseOptionalId(req.query.id),clientOrderId:parseOptionalId(req.query.client_order_id)}))}
 function list(req,res){return res.json({ok:true,items:s.list(parseOptionalId(req.query.client_order_id))})}
 function get(req,res){const id=parseOptionalId(req.params.id);if(!id)return res.status(400).json({ok:false,error:'ID invalide'});const row=s.get(id);if(!row)return res.status(404).json({ok:false,error:'Fiche Escalier V2 introuvable'});return res.json({ok:true,item:s.item(row)})}
 function remove(req,res){const id=parseOptionalId(req.params.id);if(!id)return res.status(400).json({ok:false,error:'ID invalide'});const row=s.get(id);if(!row)return res.status(404).json({ok:false,error:'Fiche Escalier V2 introuvable'});try{const result=s.remove(row);if(!result.changes)return res.status(404).json({ok:false,error:'Fiche Escalier V2 introuvable'});return res.json({ok:true,deletedId:id,redirect:'/outils/prises-cotes/escalier-v2'})}catch(e){logger.error('Erreur suppression fiche Escalier V2:',e);return res.status(500).json({ok:false,error:'Erreur suppression fiche Escalier V2'})}}
 function listPhotos(req,res){const id=parseOptionalId(req.params.id);if(!id)return res.status(400).json({ok:false,error:'ID invalide'});const row=s.get(id);if(!row)return res.status(404).json({ok:false,error:'Fiche Escalier V2 introuvable'});return res.json({ok:true,slots:photos.list(row)})}
 function addPhotos(req,res){upload(req,res,error=>{if(error)return res.status(400).json({ok:false,error:error.message||'Upload impossible'});const id=parseOptionalId(req.params.id);if(!id)return res.status(400).json({ok:false,error:'ID invalide'});const row=s.get(id);if(!row)return res.status(404).json({ok:false,error:'Fiche Escalier V2 introuvable'});if(!Array.isArray(req.files)||!req.files.length)return res.status(400).json({ok:false,error:'Aucune photo recue'});const slots=photos.add(row,req.body?.category,req.files);return res.json({ok:true,slots:photos.publicSlots(id,slots)})})}
 function caption(req,res){const id=parseOptionalId(req.params.id),photoId=String(req.params.photoId||'').trim();if(!id||!photoId)return res.status(400).json({ok:false,error:'Parametres invalides'});const row=s.get(id);if(!row)return res.status(404).json({ok:false,error:'Fiche Escalier V2 introuvable'});const slots=photos.caption(row,photoId,String(req.body?.caption||'').trim().slice(0,300));return res.json({ok:true,slots:photos.publicSlots(id,slots)})}
 function deletePhoto(req,res){const id=parseOptionalId(req.params.id),photoId=String(req.params.photoId||'').trim();if(!id||!photoId)return res.status(400).json({ok:false,error:'Parametres invalides'});const row=s.get(id);if(!row)return res.status(404).json({ok:false,error:'Fiche Escalier V2 introuvable'});const slots=photos.remove(row,photoId);if(!slots)return res.status(404).json({ok:false,error:'Photo introuvable'});return res.json({ok:true,slots:photos.publicSlots(id,slots)})}
 function file(req,res){const id=parseOptionalId(req.params.id),photoId=String(req.params.photoId||'').trim();if(!id||!photoId)return res.status(400).send('Parametres invalides');const row=s.get(id);if(!row)return res.status(404).send('Fiche Escalier V2 introuvable');const filePath=photos.resolve(row,photoId);if(!filePath)return res.status(404).send('Photo introuvable');if(!fs.existsSync(filePath))return res.status(404).send('Fichier introuvable');return res.sendFile(filePath)}
 function page(req,res){return res.sendFile(path.join(publicDir,'escalier-v2.html'))}
 return{bootstrap,list,get,remove,listPhotos,addPhotos,caption,deletePhoto,file,page};}
module.exports={createMeasurementStairV2Controller};
