'use strict';
function createMeasurementPhotosController(d={}){const{s,parseOptionalId,upload,fs,logger=console}=d;
 const valid=(id)=>{const row=s.getClassicMeasurement(id);return row&&row.module!=='Escalier V2'};
 function list(req,res){const id=parseOptionalId(req.params.id);if(!id)return res.status(400).json({ok:false,error:'ID fiche invalide'});if(!valid(id))return res.status(404).json({ok:false,error:'Fiche classique introuvable'});return res.json({ok:true,photos:s.listPhotos(id)})}
 function add(req,res){upload(req,res,error=>{const files=Array.isArray(req.files)?req.files:[];const cleanup=()=>files.forEach(f=>{if(f?.path&&fs.existsSync(f.path))fs.unlinkSync(f.path)});if(error){cleanup();return res.status(400).json({ok:false,error:error.message||'Upload impossible'})}const id=parseOptionalId(req.params.id);if(!id||!files.length){cleanup();return res.status(400).json({ok:false,error:id?'Aucune photo recue':'ID fiche invalide'})}try{const result=s.storeUploads(id,files);return res.json({ok:true,...result})}catch(e){cleanup();logger.error('Erreur stockage photo prise de cote:',e);return res.status(500).json({ok:false,error:'Impossible de stocker la photo'})}})}
 function caption(req,res){const id=parseOptionalId(req.params.id),photoId=String(req.params.photoId||'').trim();if(!id||!photoId)return res.status(400).json({ok:false,error:'Parametres invalides'});const result=s.updateCaption(id,photoId,String(req.body?.caption||'').trim().slice(0,300));if(!result.changes)return res.status(404).json({ok:false,error:'Photo introuvable'});return res.json({ok:true,photos:s.listPhotos(id)})}
 function remove(req,res){const id=parseOptionalId(req.params.id),photoId=String(req.params.photoId||'').trim();if(!id||!photoId)return res.status(400).json({ok:false,error:'Parametres invalides'});const photo=s.getPhoto(id,photoId);if(!photo)return res.status(404).json({ok:false,error:'Photo introuvable'});try{s.deletePhoto(id,photo);return res.json({ok:true,photos:s.listPhotos(id)})}catch(e){logger.error('Erreur suppression photo prise de cote:',e);return res.status(500).json({ok:false,error:'Suppression photo impossible'})}}
 function file(req,res){const id=parseOptionalId(req.params.id),photoId=String(req.params.photoId||'').trim();if(!id||!photoId)return res.status(400).send('Parametres invalides');const photo=s.getPhoto(id,photoId);if(!photo)return res.status(404).send('Photo introuvable');try{const p=s.resolvePhotoFile(id,photo);if(!fs.existsSync(p))return res.status(404).send('Fichier photo introuvable');res.type(photo.mime_type||'application/octet-stream');return res.sendFile(p)}catch{return res.status(400).send('Chemin photo invalide')}}
 return{list,add,caption,remove,file};}
module.exports={createMeasurementPhotosController};
