'use strict';
function createMeasurementsController(d={}){const{s,renderList,renderDetail,pageTemplate,viewDeps,parseOptionalId,normalizeQuoteStatus,measurementRoutes,measurementTitle}=d;
 function list(req,res){return res.send(pageTemplate(req,'Prises de cotes',renderList({savedMeasurements:s.listMeasurements()},viewDeps)))}
 function options(req,res){const data=s.linkOptions();return res.json({quotes:data.quotes.map(q=>({id:q.id,label:`#${q.id} - ${q.client_name||'Client non renseigné'} - ${q.title||'Sans titre'} - ${normalizeQuoteStatus(q.status)}`})),clientOrders:data.clientOrders.map(o=>({id:o.id,label:`#${o.id} - ${o.name||'Client'} - ${o.description||'Commande'} - ${o.status||'En cours'}`}))})}
 function context(req,res){const id=parseOptionalId(req.query.quote_id);if(!id)return res.status(400).json({ok:false,error:'ID devis invalide'});const q=s.quoteContext(id);if(!q)return res.status(404).json({ok:false,error:'Devis introuvable'});return res.json({ok:true,quote:{id:q.id,client:String(q.client_name||'').trim(),chantier:String(q.title||'').trim()}})}
 function save(req,res){return res.json({ok:true,id:s.saveMeasurement(req.body||{})})}
 function get(req,res){const id=parseOptionalId(req.params.id);if(!id)return res.status(400).json({ok:false,error:'ID prise de cote invalide'});const row=s.getMeasurementById(id);if(!row)return res.status(404).json({ok:false,error:'Prise de cote introuvable'});const p=s.editorPayload(row);return res.json({ok:true,measurement:p.measurement,returnUrl:p.returnUrl})}
 function remove(req,res){const id=parseOptionalId(req.params.id);if(!id)return res.status(400).json({ok:false,error:'ID prise de cote invalide'});if(!s.getMeasurementById(id))return res.status(404).json({ok:false,error:'Prise de cote introuvable'});try{const result=s.deleteMeasurement(id);if(!result.changes)return res.status(404).json({ok:false,error:'Prise de cote introuvable'});return res.json({ok:true,deletedId:id,redirect:'/outils/prises-cotes'})}catch(e){console.error('Erreur suppression prise de cote:',e);return res.status(500).json({ok:false,error:'Erreur suppression prise de cote'})}}
 function detail(req,res){const id=parseOptionalId(req.params.id);if(!id)return res.status(400).send('ID prise de cote invalide');const row=s.getMeasurementById(id);if(!row)return res.status(404).send('Prise de cote introuvable');const canonical=measurementRoutes.canonicalMeasurementUrl(row,{fromQuoteId:req.query.from_quote});if(canonical)return res.redirect(302,canonical);const p=s.editorPayload(row);return res.send(pageTemplate(req,measurementTitle(row),renderDetail({measurement:row,editorPayload:p.measurement,id},viewDeps)))}
 return{list,options,context,save,get,remove,detail};}
module.exports={createMeasurementsController};
