'use strict';
function createMeasurementTechnicalDrawingService({db,parseOptionalId,parseMeasurementData,randomUUID,buildStairPhotoSlots,now=()=>new Date().toISOString()}={}){
 const makeId=()=>`sketch-${randomUUID()}`;
 function normalize(value){return(Array.isArray(value)?value:[]).filter(x=>x&&typeof x==='object').map((x,i)=>({id:String(x.id||makeId()).trim(),title:String(x.title||`Croquis ${i+1}`).trim(),data:x.data&&typeof x.data==='object'?x.data:x,preview:typeof x.preview==='string'?x.preview:'',updatedAt:String(x.updatedAt||now())}))}
 function getContext(value){const id=parseOptionalId(value);if(!id)return null;const row=db.prepare('SELECT * FROM measurements WHERE id = ?').get(id);if(!row)return null;const payload=parseMeasurementData(row.data),fields=payload.fields&&typeof payload.fields==='object'?payload.fields:{};return{id,row,payload,fields,sketches:normalize(fields.technical_drawing_sketches)}}
 function save(entry,sketches){const next=normalize(sketches);entry.payload.fields={...(entry.fields||{}),technical_drawing_sketches:next,technical_drawing_version:2};db.prepare('UPDATE measurements SET data = ?, updated_at = ? WHERE id = ?').run(JSON.stringify(entry.payload),now(),entry.id);return next}
 function preserve(bodyValue,existingId){const body=bodyValue&&typeof bodyValue==='object'?bodyValue:{},fields=body.fields&&typeof body.fields==='object'?body.fields:{};if(Object.prototype.hasOwnProperty.call(fields,'technical_drawing_sketches'))return body;const existing=parseOptionalId(existingId)?db.prepare('SELECT data FROM measurements WHERE id = ?').get(existingId):null;if(!existing)return body;const previous=parseMeasurementData(existing.data),old=previous.fields&&typeof previous.fields==='object'?previous.fields:{};if(!Array.isArray(old.technical_drawing_sketches))return body;return{...body,fields:{...fields,technical_drawing_sketches:old.technical_drawing_sketches,technical_drawing_version:old.technical_drawing_version||2}}}
 function list(entry){return entry.sketches.map((s,i)=>({id:s.id,title:s.title||`Croquis ${i+1}`,preview:s.preview||'',updatedAt:s.updatedAt||null,url:`/outils/prises-cotes/${entry.id}/croquis/${encodeURIComponent(s.id)}`}))}
 function create(entry,titleValue){const title=String(titleValue||'').trim()||`Croquis ${entry.sketches.length+1}`,sketch={id:makeId(),title,data:{id:makeId(),title,strokes:[],annotations:[],backgroundImage:'',updatedAt:now()},preview:'',updatedAt:now()},saved=save(entry,entry.sketches.concat(sketch));return saved.find(x=>x.id===sketch.id)||sketch}
 function photos(entry){if(String(entry.row.module||'')==='Escalier V2')return buildStairPhotoSlots(entry.id,entry.fields.photo_slots);const list=Array.isArray(entry.payload.photos)?entry.payload.photos:[];return[{category:'Photos',count:list.length,photos:list.map((p,i)=>({id:String(p.id||p.name||`photo-${i}`),fileName:String(p.name||`Photo ${i+1}`),caption:String(p.caption||p.name||`Photo ${i+1}`),url:String(p.dataUrl||p.url||'')})).filter(p=>p.url)}]}
 function update(entry,sketchId,body={}){const index=entry.sketches.findIndex(x=>x.id===sketchId);if(index<0)return null;const title=String(body.title||entry.sketches[index].title||'').trim()||`Croquis ${index+1}`,data=body.data&&typeof body.data==='object'?body.data:{},preview=typeof body.preview==='string'?body.preview:entry.sketches[index].preview,next=entry.sketches.slice();next[index]={id:sketchId,title,data,preview,updatedAt:now()};return save(entry,next)[index]}
 function remove(entry,sketchId){const next=entry.sketches.filter(x=>x.id!==sketchId);if(next.length===entry.sketches.length)return false;save(entry,next);return true}
 return{normalize,getContext,save,preserve,list,create,photos,update,remove};}
module.exports={createMeasurementTechnicalDrawingService};
