'use strict';
const MODULE='Escalier V2';
function createMeasurementStairV2Service({db,parseOptionalId,parseMeasurementData,buildPhotoSlots,photoBaseDir,safeResolveInside,photoRoot,path,removeStoragePathIfExists,sketchPath}={}){
 function bootstrap({id,clientOrderId}){const prefill={client:'',commande:'',client_order_id:clientOrderId},order=clientOrderId?db.prepare('SELECT id, name, description FROM client_orders WHERE id = ?').get(clientOrderId):null;let linkedDraftId=null;if(order){prefill.client=String(order.name||'').trim();prefill.commande=String(order.description||`Commande_${order.id}`).trim();linkedDraftId=db.prepare('SELECT id FROM measurements WHERE module = ? AND client_order_id = ? ORDER BY updated_at DESC, id DESC LIMIT 1').get(MODULE,clientOrderId)?.id||null;}let currentDraftId=id&&db.prepare('SELECT id FROM measurements WHERE id = ? AND module = ?').get(id,MODULE)?.id||null;if(!currentDraftId&&linkedDraftId)currentDraftId=linkedDraftId;return{module:MODULE,prefill,linkedDraftId,currentDraftId};}
 function get(id){return db.prepare('SELECT * FROM measurements WHERE id = ? AND module = ?').get(id,MODULE)}
 function list(clientOrderId){const rows=clientOrderId?db.prepare('SELECT * FROM measurements WHERE module = ? AND client_order_id = ? ORDER BY updated_at DESC, id DESC').all(MODULE,clientOrderId):db.prepare('SELECT * FROM measurements WHERE module = ? ORDER BY updated_at DESC, id DESC').all(MODULE);return rows.map(row=>{const p=parseMeasurementData(row.data),f=p.fields&&typeof p.fields==='object'?p.fields:{};return{id:row.id,recordName:row.record_name||`Fiche Escalier V2 #${row.id}`,client:row.client||f.client||'',commande:f.commande||'',chantier:row.chantier||f.chantier||'',date:row.measure_date||f.date||'',metreur:f.metreur||'',referenceInterne:f.reference_interne||'',typeEscalier:f.type_escalier||'Autre',statut:f.statut||'Brouillon',quote_id:parseOptionalId(row.quote_id),client_order_id:parseOptionalId(row.client_order_id),updatedAt:row.updated_at||row.created_at||null}})}
 function item(row){const p=parseMeasurementData(row.data),f=p.fields&&typeof p.fields==='object'?p.fields:{};return{id:row.id,module:row.module,recordName:row.record_name,quote_id:parseOptionalId(row.quote_id),client_order_id:parseOptionalId(row.client_order_id),fields:f,photoSlots:buildPhotoSlots(row.id,f.photo_slots),updatedAt:row.updated_at||row.created_at||null}}
 function remove(row){const dirs=[photoBaseDir(row),safeResolveInside(photoRoot,String(row.id))],unique=Array.from(new Set(dirs.map(d=>path.resolve(d))));unique.forEach(removeStoragePathIfExists);removeStoragePathIfExists(sketchPath('measurements',row.id));return db.prepare('DELETE FROM measurements WHERE id = ? AND module = ?').run(row.id,MODULE)}
 return{MODULE,bootstrap,get,list,item,remove};}
module.exports={createMeasurementStairV2Service};
